### PR TITLE
samples: lvgl: add configuration file for ek_ra8d1 board

### PR DESCRIPTION
**Pull request by uLipe**
To simplify the build command. With this modification the only extra argument needed is the shield required to build the samples for lvgl module and display subsys.

### CODE REVIEW

**Comment by uLipe** [comment]
@thaoluonguw do you think this PR should be added here, or moved directly to the Zephyr upstream?

Thank you!

**Comment by thaoluonguw** [comment]
> @thaoluonguw do you think this PR should be added here, or moved directly to the Zephyr upstream?

Hello @uLipe , I am sorry for late reply.
We already have a PR for this: https://github.com/zephyrproject-rtos/zephyr/pull/80694.
Except CONFIG_LV_USE_PERF_MONITOR isn't enable as default, others are similar.
Could you take a look and if you have any comment, please tell us too.
Thank you so much.

**Comment by uLipe** [comment]
@thaoluonguw great to hear that, I ll go through the PR on the upstream also :)

**Comment by uLipe** [comment]
CLosing this one, since there is a PR with these changes landing to the upstream

**Pull request closed without merging**
